name = "classic-cafe"
main = "worker.js"
compatibility_date = "2026-08-24"

[assets]
directory = "."

[[d1_databases]]
binding = "DB"
database_name = "classic-cafe-orders"
database_id = "d880a60e-d779-44bd-8ad3-40b845f3bf18"
