name = "classic-cafe-jodhpur"
main = "worker.js"
compatibility_date = "2026-08-22"

[assets]
directory = "."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "classic-cafe-orders"
database_id = "d880a60e-d779-44bd-8ad3-40b845f3bf18"
